version: '2'
services:
  base:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
  dev:
    extends: base
    environment:
      - RAILS_ENV=development
    command: bash -c "./run-dev.sh"

  prod:
   extends: base
   environment:
     - RAILS_ENV=production
     - RAILS_SERVE_STATIC_FILES=true
     - SECRET_KEY_BASE=`rails secret`
   command: bash -c "./run-prod.sh"

  test:
    extends: base
    command: bash -c "rails test -e test"
